version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $ap-south-1 | docker login --username AWS --password-stdin $008971679675.dkr.ecr.ap-south-1.amazonaws.com/my-app
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t my-app .
      - docker tag my-app:latest $ECR_REGISTRY/my-app:latest
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push $ECR_REGISTRY/my-app:latest
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
