version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $ap-south-1 | docker login --username AWS --password-stdin $008971679675.dkr.ecr.ap-south-1.amazonaws.com/myecrrepo
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $myecrepo:$latest .
      - docker tag $IMAGE_NAME:$IMAGE_TAG $ECR_REGISTRY/$IMAGE_NAME:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $ECR_REGISTRY/$IMAGE_NAME:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"%s","imageUri":"%s"}]' $IMAGE_NAME $ECR_REGISTRY/$IMAGE_NAME:$IMAGE_TAG > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
