phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 008971679675.dkr.ecr.ap-south-1.amazonaws.com/my-eks
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $ECR_REGISTRY/$my-eks:latest .
      - docker tag $ECR_REGISTRY/$my-eks:latest $ECR_REGISTRY/$my-eks:$COMMIT_HASH
  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      - docker push $ECR_REGISTRY/$REPOSITORY_NAME:latest
      - docker push $ECR_REGISTRY/$REPOSITORY_NAME:$COMMIT_HASH
