apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-eks
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-eks
  template:
    metadata:
      labels:
        app: my-eks
    spec:
      containers:
      - name: my-eks-container
        image: 008971679675.dkr.ecr.ap-south-1.amazonaws.com/my-eks:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: my-eks-service
  namespace: default
spec:
  selector:
    app: my-eks
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
